"""Deprecated. The figures in this repository are now generated by scripts
that drive the actual `ris_sim.core.engine.Simulation`, not by canned numpy
arrays. Use:

    python -m paper.figures_src.run_all

to regenerate every figure (PDF + raw CSV + reproducibility sidecar) in
``paper/figures/`` and ``paper/figures_data/``.
"""

from __future__ import annotations

import sys


def main() -> int:
    print(__doc__)
    print("Forwarding to paper.figures_src.run_all ...\n")
    from paper.figures_src.run_all import main as run_all_main
    return run_all_main()


if __name__ == "__main__":
    sys.exit(main())
